#源文件
File = 11_信号灯集合和共享内存的生产者与消费者.c

AppA = 11_A.out
AppB = 11_B.out
AppC = 11_C.out

bianyi:
	gcc ${File} -D Creat -o ${AppA} -g
	gcc ${File} -D Write -o ${AppB} -g
	gcc ${File} -D Read -o ${AppC} -g
